repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: trailing-whitespace
    - id: requirements-txt-fixer
    - id: end-of-file-fixer
    - id: check-added-large-files
      args: [--maxkb=500]

  - repo: https://github.com/pycqa/isort
    rev: 5.5.4
    hooks:
    -   id: isort
        files: "\\.(py)$"
